version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis-project-redis
    ports:
      - "6379:6379"

  load-dataset:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-project-load-dataset
    command: ["node", "dist/loadDataset.js"]
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-project-app
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - load-dataset
    environment:
      - REDIS_URL=redis://redis:6379
